<?php
/**
 * @var $this Template
 * @var $contactsModel ContactsModel
 * @var $categoriesModel CategoriesModel
 */
$contactsModel = $this->getModel('contacts');
$categoriesModel = $this->getModel('categories');

/**
 * @var $contact Contact
 */
$contact = $contactsModel->getOneById($this->elementId);
?>

<?php include_once('elements/head.phtml'); ?>

<div class="container-fluid">
    <div class="row content">

        <?php include_once('elements/menu.phtml');?>

        <div class="col-sm-10">
            <h1><small><?php echo $this->getPageLabel(); ?></small></h1>
            <hr>
            <form action="?action=list" method="post">
                <input type="hidden"  name="model" value="contacts" />
                <input type="hidden"  name="id"
                       value="<?php if($this->action == 'edit') echo $contact->getId(); ?>" />

                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="name">Name*:</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter name" required
                            value="<?php if(!empty($contact)) echo $contact->getName(); ?>" />
                    </div>

                    <div class="form-group">
                        <label for="name">Surname*:</label>
                        <input type="text" class="form-control" name="surname" id="surname"  placeholder="Enter surname" required
                               value="<?php if(!empty($contact)) echo $contact->getSurname(); ?>" />
                    </div>

                    <div class="form-group">
                        <label for="name">Phone:</label>
                        <input type="text" class="form-control" name="phone" id="phone"  placeholder="Enter phone number"
                               value="<?php if(!empty($contact)) echo $contact->getPhone(); ?>" />
                    </div>

                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="name">Email:</label>
                        <input type="text" class="form-control" name="email" id="email"  placeholder="Enter email address"
                               value="<?php if(!empty($contact)) echo $contact->getEmail(); ?>" />
                    </div>

                    <div class="form-group">
                        <label for="name">Address:</label>
                        <input type="text" class="form-control" name="address" id="address"  placeholder="Enter address"
                               value="<?php if(!empty($contact)) echo $contact->getAddress(); ?>" />
                    </div>

                    <div class="form-group">
                        <label for="sel1">Category*:</label>
                        <select class="form-control" name="categoryId" id="sel1" required>
                            <option value="" disabled selected>Choose a category</option>
                            <?php foreach ($categoriesModel->getAll() as $category): ?>
                                <option value="<?php echo $category->getId(); ?>"
                                    <?php if($this->isSelectSelected($category, $contact)) echo ' selected ';?> >
                                    <?php echo $category->getLabel(); ?>
                                </option>
                            <?php endforeach;?>

                        </select>
                    </div>
                </div>

                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="note">Note:</label>
                        <textarea placeholder="Enter note" class="form-control" rows="5" name="note" id="note"><?php if(!empty($contact)) echo $contact->getNote(); ?></textarea>
                    </div>
                </div>

                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success float-right">Save</button>
                </div>

            </form>
        </div>
    </div>
</div>

<?php include_once('elements/footer.phtml'); ?>