<?php include_once('elements/head.phtml'); ?>

<div class="container-fluid">
    <div class="row content">

        <?php include_once('elements/menu.phtml');?>

        <div class="col-sm-10">
            <h1><small><?php echo $this->getPageLabel(); ?></small></h1>
            <hr>
            <p>Welcome to contact list</p>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml'); ?>