<?php
/**
 * @var $this Template
 * @var $contactsModel ContactsModel
 * @var $categoriesModel CategoriesModel
 */
$contactsModel = $this->getModel('contacts');
$categoriesModel = $this->getModel('categories');

/**
 * @var $contacts array of Contact
 */
$contacts = $contactsModel->getAll();
?>

<?php include_once('elements/head.phtml'); ?>

<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>

        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel() . ' (' . count($contacts) . ')' ?></small>
            </h1>
            <div class="up_button">
                <a href="?action=add"
                   data-toggle="tooltip" title="Add contact" data-placement="left" >
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Category</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        /**
                         * @var $contact Contact
                         */
                        foreach ($contacts as $nr => $contact):
                    ?>

                        <tr>
                            <th scope="row"><?php echo $nr+1; ?></th>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>"><?php echo $contact->getName(); ?></a></td>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>"><?php echo $contact->getSurname(); ?></a></td>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>"><?php echo $contact->getPhone(); ?></a></td>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>"><?php echo $contact->getEmail(); ?></a></td>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>"><?php echo $contact->getAddress(); ?></a></td>
                            <td><a href="/?action=contact&id=<?php echo $contact->getId(); ?>">
                                    <?php echo $categoriesModel->getCategoryLabelById($contact->getCategoryId()); ?>
                                </a>
                            </td>
                            <td>
                                <a href="?action=edit&id=<?php echo $contact->getId(); ?>"
                                    data-toggle="tooltip" title="Edit" data-placement="left" >
                                    <button type="button" class="btn btn-primary">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </a>
                                <a href="?action=delete&id=<?php echo $contact->getId(); ?>"
                                    data-toggle="tooltip" title="Delete" data-placement="right" >
                                    <button type="button" class="btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </a>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include_once('elements/footer.phtml'); ?>
